### ISSUE TITLE
Error loading ciarp ds

### ISSUE THREAD

**Issue by ulises-jeremias** [midusi/handshape_datasets#18]
```python
>>> import handshape_datasets as ds
>>> ds
<module 'handshape_datasets' from '/tf/lib/handshape_datasets/handshape_datasets/__init__.py'>
>>> ds.load("ciarp")
WARNING:root:Creating folder /.handshape_datasets/ciarp for the dataset ciarp
WARNING:root:Downloading ciarp.zip from http://home.agh.edu.pl/~bkw/code/ciarp2017/ciarp.zip
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/tf/lib/handshape_datasets/handshape_datasets/__init__.py", line 41, in load
    return dataset.get(folderpath, **kwargs)
  File "/tf/lib/handshape_datasets/handshape_datasets/datasets_helpers/dataset_loader.py", line 50, in ge
t
    self.download_dataset(path)
  File "/tf/lib/handshape_datasets/handshape_datasets/datasets_helpers/ciarp.py", line 24, in download_da
taset
    filename=self._FILENAME)
  File "/tf/lib/handshape_datasets/handshape_datasets/datasets_helpers/utils.py", line 37, in download_file
    with open(filepath, 'wb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/.handshape_datasets/ciarp/ciarp.zip/ciarp.zip'
```

**Comment by facundoq** [comment]
fixed by c568a79
